version: '3'

tasks:

  deps:install:
    desc: Install the project dependencies
    cmds:
      - go mod download

  deps:tidy:
    desc: Clean go.mod
    cmds:
      - go mod tidy

  lint:
    desc: Format source and test files
    cmds:
      - golangci-lint run ./...

  build:
    desc: Format source and test files
    cmds:
      - go build -v ./...

  test:
    desc: Run the unit tests
    cmds:
      - go test -v ./...
    pre:
      - task: env:activate

  repl:
    desc: Start REPL
    cmds:
      - go run main.go

  run:
    desc: Run test.eve file
    cmds:
      - go run main.go run ./test.eve