name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: "on"

    - name: Build
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: "on"
      run: go build -v ./...

    - name: Test
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: "on"
      run: go test -v ./...

    - name: Format check
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: "on"
      run: test -z $(gofmt -l .)

    - name: Lint
      env:
          GOPATH: ${{ runner.workspace }}
          GO111MODULE: "on"
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
        golangci-lint run